[project]
name = "asteroids"
version = "0.1.0"
description = "This is my second [Boot.dev] (https://www.boot.dev) project!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame==2.6.1",
]
